name: Publish

on:
  push:
    branches: [ master, feature/*]

jobs:
  build_and_test_and_publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release -f netcoreapp3.1 --no-restore
    - name: Publish Nuget Packages
      run: dotnet nuget push **\*.nupkg -k "$env:API_KEY" -s https://api.nuget.org/v3/index.json
      env:
        API_KEY: ${{ secrets.API_KEY }}

